<?php

define('CSV_IMPORT_PLUGIN_VERSION', '1.0.0');
define('CSV_IMPORT_DIRECTORY', dirname(__FILE__));
define('CSV_IMPORT_CSV_FILES_DIRECTORY', CSV_IMPORT_DIRECTORY . DIRECTORY_SEPARATOR . 'csv_files');
define('CSV_IMPORT_BACKGROUND_SCRIPTS_DIRECTORY', CSV_IMPORT_DIRECTORY . DIRECTORY_SEPARATOR . 'background_scripts');

define('CSV_IMPORT_COLUMN_MAP_TARGET_TYPE_RADIO_BUTTONS_PREFIX', 'csv_import_column_map_target_type_');
define('CSV_IMPORT_COLUMN_MAP_ELEMENTS_DROPDOWN_PREFIX', 'csv_import_column_elements_');


